---
title: "Team_3_Project"
output: html_document
---

```{r}
rm(list=ls())
getwd()
setwd("~/GitHub/QB2021_Team3")
```

> A bunch of packages just in case 

```{r}
package.list <- c('vegan', 'ade4', 'viridis', 'gplots', 'BiodiversityR', 'indicspecies')
  for (package in package.list) {
    if (!require(package, character.only = TRUE, quietly = TRUE)) {
      install.packages(package)
      library(package, character.only = TRUE)
    }
  }
package.list <- c('mobsim', 'knitr', 'vegan', 'tidyr', 'dplyr', 'ggplot2', 'formatR')
for (package in package.list) {
  if (!require(package, character.only = TRUE, quietly = TRUE)) {
    install.packages(package)
    library(package, character.only = TRUE)
  }
}

```
##Original Correlations plus boxplot


```{r}
library(dplyr)
library(ggplot2)

foodWebs <- read.table("135FoodWebs.txt", sep = "\t", header = TRUE, row.names = 1)
dafra <- foodWebs %>% group_by(Ecosystem.Type.ID) %>% summarise(me = mean(exp(Log.Abundance.)))

library(forcats)

foodWebs %>%
  mutate(Ecosystem.Type.ID = fct_reorder(as.factor(Ecosystem.Type.ID), exp(Log.Abundance.), .fun = 'mean')) %>%
  ggplot( aes(x = as.factor(Ecosystem.Type.ID), y = exp(Log.Abundance.))) +
    geom_boxplot() + 
    xlab("Ecosystem Type ID") +
    theme(legend.position = "none") +
    xlab("")

foodWebs %>%
  mutate(Ecosystem.Type.ID = fct_reorder(as.factor(Ecosystem.Type.ID), Log.averageMass., .fun = 'mean')) %>%
  ggplot( aes(x = as.factor(Ecosystem.Type.ID), y = Log.averageMass.)) +
    geom_boxplot() + 
    xlab("Ecosystem Type ID") +
    theme(legend.position = "none") +
    xlab("")

model = lm(I(Log.Abundance.)~as.factor(Ecosystem.Type.ID), data=foodWebs)
summary(model)


foodWebs <- read.table("135FoodWebs.txt", sep = "\t", header = TRUE, row.names = 1)

foodWebs.nums <- foodWebs[,c(6:10, 12:17, 20:22, 24:31, 33)]
pairs(foodWebs.nums)
boxplot(Log.Biomass.~Ecosystem.Type.ID, data = foodWebs,  xlab = "Ecosystem Type", ylab = "Log Biomass")

install.packages("corrplot", repos = "http://cran.rstudio.com/%22")
require("corrplot")

cor1 <- cor(foodWebs.nums)
corrplot(cor1, method = "ellipse")
```

## Correlation Coefficients 



```{r }

foodWebs$Taxon.ID = as.factor(foodWebs$Taxon.ID)
foodWebs$Ecosystem.Type.ID = as.factor(foodWebs$Ecosystem.Type.ID)


require(dplyr)
AbS <- foodWebs %>%
  group_by(Ecosystem.Type.ID) %>% 
  summarise(cor(Log.Abundance., Soil.pH))
  summarise(cor(Log.Abundance., Soil.pH))
  
AbC <- foodWebs %>%
  group_by(Ecosystem.Type.ID) %>% 
  summarise(cor(Log.Abundance., C.tot))

AbT <- foodWebs %>%
  group_by(Ecosystem.Type.ID) %>% 
  summarise(cor(Log.Abundance., Average.T))
```

##plotting with correlation coefficient lines

```{r}
if(!require(ggplot2)){install.packages("ggplot2")}
library(ggplot2)

if(!require(ggpubr)){install.packages("ggpubr")}
library(ggpubr)

model = lm(I(Log.Abundance.)~Ecosystem.Type.ID + I(N.tot), data=foodWebs)
summary(model)
model$coefficients
exp(model$coefficients)
plot(foodWebs$Log.Abundance., foodWebs$N.tot, col=as.factor(foodWebs$Ecosystem.Type.ID))
ggscatter(foodWebs, x="Log.averageMass.", y="N.tot", color="Ecosystem.Type.ID", add="reg.line")

model = lm(I(Log.Abundance.)~Ecosystem.Type.ID + I(Soil.pH), data=foodWebs)
summary(model)
model$coefficients
exp(model$coefficients)
ggplot(foodWebs$Log.Abundance., foodWebs$Soil.pH, col=as.factor(foodWebs$Ecosystem.Type.ID))
ggplot(foodWebs, x="Log.Abundance", y="Soil.pH", color="Ecosystem.Type.ID", add="reg.line")

model = lm(I(Log.abundance.)~Ecosystem.Type.ID, data=foodWebs)
summary(model)
model$coefficients
exp(model$coefficients)
plot(foodWebs$Log.averageMass., foodWebs$Soil.pH, col=as.factor(foodWebs$Ecosystem.Type.ID))
ggscatter(foodWebs, x="Log.averageMass.", y="Soil.pH", color="Ecosystem.Type.ID", add="reg.line")

model1 = lm(I(Log.averageMass.)~Ecosystem.Type.ID + I(Mean.rainfall), data=foodWebs)
summary(model)
model1$coefficients
exp(model$coefficients)
plot(foodWebs$Log.averageMass., foodWebs$Mean.rainfall, col=as.factor(foodWebs$Ecosystem.Type.ID))
ggscatter(foodWebs, x="Log.averageMass.", y="Mean.rainfall", color="Ecosystem.Type.ID", add="reg.line")
```

https://tidyr.tidyverse.org/reference/pivot_wider.html  
 IDK yet
```{r}
#foodWebs %>%
  
newData <- select(foodWebs, Web.ID, Genus.Morphon, Log.Abundance.)
matrix <- pivot_wider(newData, names_from = Genus.Morphon,
              values_from = c(Log.Abundance.) , values_fill = 0
             )

matrix.db <- vegdist(matrix, method = "bray", upper = TRUE, diag = TRUE)

order <- rev(attr(matrix.db, "Labels"))

levelplot(as.matrix(matrix.db), aspect = "iso", col.regions = inferno, xlab = NULL, ylab = NULL, scales = list(cex = 0.5), main = "Bray-Curtis Distance", )
#69-87 (the points that are all similar to each other) are all ecosystem id 6, or pine forests
```




```{r}
newData$Ecosystem.Type.ID <- foodWebs$Ecosystem.Type.ID
matrixEco <- pivot_wider(newData, names_from = Genus.Morphon,
              values_from = c(Log.Abundance.) , values_fill = 0
             )
EcoID <- as.factor(matrixEco$Ecosystem.Type.ID)

pcoa <- cmdscale(matrix.db, eig = TRUE, k = 3)

explainvar1 <- round(pcoa$eig[1] / sum(pcoa$eig), 3) * 100
explainvar2 <- round(pcoa$eig[2] / sum(pcoa$eig), 3) * 100
explainvar3 <- round(pcoa$eig[3] / sum(pcoa$eig), 3) * 100
sum.eig <- sum(explainvar1, explainvar2, explainvar3)

par(mar = c(5, 5, 1, 2) + 0.1)

plot(pcoa$points[ ,1], pcoa$points[ ,2], ylim = c(-0.2, 0.7),
     xlab = paste("PCoA 1 (", explainvar1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", explainvar2, "%)", sep = ""),
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = F)

axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)
palette(col.rainbow <- rainbow(7))
points(pcoa$points[,1], pcoa$points[,2],
       pch = 19, cex = 3, col=EcoID)
text(pcoa$points[,1], pcoa$points[, 2],
     labels = row.names(pcoa$points))
legend("topright", legend = c(1:7), col = c(rainbow(7)), cex =0.8, lty = 1, lwd = 3)

matrixTaxa <- pivot_wider(newData, names_from = Genus.Morphon,
              values_from = c(Log.Abundance.) , values_fill = 0
             )


newMatrix <- matrix[,2:259]
ecoREL <- newMatrix
  for(i in 1:nrow(newMatrix)){
    ecoREL[i,] = newMatrix[i,]/ sum(newMatrix[i,])
  }
cols <- colnames(ecoREL)
#eco.pcoa <- add.spec.scores(pcoa,cols, method = "pcoa.scores")
#text(eco.pcoa$cproj[,1], eco.pcoa$cproj[,2],
#     labels = row.names(eco.pcoa$cproj), col = "black")
```




```{r}
enviro <- foodWebs[,c(1, 9, 10, 13, 18, 26, 28, 32:33)]
enviroPivot <- pivot_wider(enviro, names_from = Web.ID)


matrix.db <- vegdist(matrix, method = "bray")


matrix.dbrda <-dbrda(matrix.db ~ ., as.data.frame(enviroPivot))
ordiplot(matrix.dbrda)
matrix.dbrda.mod0 <- dbrda(matrix.db ~ 1, as.data.frame(enviroPivot))
ordiplot(matrix.dbrda.mod0)
matrix.dbrda.mod1 <- dbrda(matrix.db ~ ., as.data.frame(enviroPivot))
matrix.dbrda <- ordiR2step(matrix.dbrda.mod0, matrix.dbrda.mod1, perm.max = 200)
matrix.dbrda$call
matrix.dbrda$anova
ordiplot(matrix.dbrda)
permutest(matrix.dbrda, permutations = 999)
envfit(matrix.dbrda, enviroPivot[,], perm = 999)
matrix.explainvar1 <- round(matrix.dbrda$CCA$eig[1]/
                            sum(c(matrix.dbrda$CCA$eig, matrix.dbrda$CA$eig)), 3) * 100
matrix.explainvar2 <- round(matrix.dbrda$CCA$eig[2] /
                             sum(c(matrix.dbrda$CCA$eig, matrix.dbrda$CA$eig)), 3) *100
par(mar = c(5, 5, 4, 4) +0.1)
plot(scores(matrix.dbrda, display = "wa"), xlim = c(-1.3, 1.1), ylim = c(-1.1, 2.7), 
     xlab = paste("dbRDA 1 (", matrix.explainvar1, "%", sep = ""), 
     ylab = paste("dbRDA 2 (", matrix.explainvar2, "%)", sep = ""),
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = FALSE)
axis(side = 1, labels = T, lwd.ticks =2, cex.axis = 1.2, las =1)
axis(side = 2, labels = T, lwd.ticks =2, cex.axis = 1.2, las =1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)
points(scores(matrix.dbrda, display = "wa"), pch = 19, cex = 3, bg = "gray", col = "gray")
text(scores(matrix.dbrda, display = "wa"), labels = row.names(scores(matrix.dbrda, display = "wa")))

vectors <- scores(matrix.dbrda, display = "bp")

arrows(0, 0, vectors[,1], vectors[,2], lwd = 2, lty = 1, length = 0.2, col = "red")
text(vectors[,1], vectors[,2], pos = 3, labels = row.names(vectors))
axis(side = 3, lwd.ticks = 2, cex.axis = 1.2, las = 1, col = "red", lwd = 2.2, at = pretty(range(vectors[,1])) * 2, labels = pretty(range(vectors[,1])))
axis(side = 4,lwd.ticks = 2, cex.axis = 1.2, las = 1, col = "red", lwd = 2.2, at = pretty(range(vectors[,2])) * 2, labels = pretty(range(vectors[,2])))
```




```{r}
massData <- select(foodWebs, Web.ID, Genus.Morphon, Log.averageMass.)
#massData$Log.averageMass. <- exp(massData$Log.averageMass.) #had to exponentiate log average mass because there were negative numbers
massmatrix <- pivot_wider(massData, names_from = Genus.Morphon,
              values_from = c(Log.averageMass.) , values_fill = 0
             )

massmatrix.db <- vegdist(massmatrix, method = "bray", upper = TRUE, diag = TRUE)

EcoID <- as.factor(matrixEco$Ecosystem.Type.ID)

pcoaMass <- cmdscale(massmatrix.db, eig = TRUE, k = 3)

explainvar1 <- round(pcoaMass$eig[1] / sum(pcoaMass$eig), 3) * 100
explainvar2 <- round(pcoaMass$eig[2] / sum(pcoaMass$eig), 3) * 100
explainvar3 <- round(pcoaMass$eig[3] / sum(pcoaMass$eig), 3) * 100
sum.eig <- sum(explainvar1, explainvar2, explainvar3)

par(mar = c(5, 5, 1, 2) + 0.1)

plot(pcoaMass$points[ ,1], pcoaMass$points[ ,2], ylim = c(-0.2, 0.7),
     xlab = paste("PCoA 1 (", explainvar1, "%)", sep = ""),
     ylab = paste("PCoA 2 (", explainvar2, "%)", sep = ""),
     pch = 16, cex = 2.0, type = "n", cex.lab = 1.5, cex.axis = 1.2, axes = F)

axis(side = 1, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
axis(side = 2, labels = T, lwd.ticks = 2, cex.axis = 1.2, las = 1)
abline(h = 0, v = 0, lty = 3)
box(lwd = 2)
palette(col.rainbow <- rainbow(7))
points(pcoaMass$points[,1], pcoaMass$points[,2],
       pch = 19, cex = 3, col=EcoID)
text(pcoaMass$points[,1], pcoaMass$points[, 2],
     labels = row.names(pcoaMass$points))
legend("topright", legend = c(1:7), col = c(rainbow(7)), cex =0.8, lty = 1, lwd = 3)


order <- rev(attr(massmatrix.db, "Labels"))

levelplot(as.matrix(massmatrix.db), aspect = "iso", col.regions = inferno, xlab = NULL, ylab = NULL, scales = list(cex = 0.5), main = "Bray-Curtis Distance", )

```
